DROP DATABASE IF EXISTS hsj;
CREATE DATABASE hsj;

USE hsj;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    point INT DEFAULT 0
);

SET SQL_SAFE_UPDATES = 0;
DELETE FROM users;
SET SQL_SAFE_UPDATES = 1;

#INSERT INTO users (user_id, point) VALUES ('asd', 0);

SELECT * FROM users;

#SET SQL_SAFE_UPDATES = 0;
#UPDATE users SET point = 0 WHERE id = 1;
#SET SQL_SAFE_UPDATES = 1;

